# Generated by Django 4.1.5 on 2023-01-31 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AddField(
            model_name='offer',
            name='brand',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='admin_app.brand'),
            preserve_default=False,
        ),
    ]
