# Generated by Django 4.1.5 on 2023-01-31 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_alter_image_image_1_alter_image_image_2_and_more'),
        ('offers', '0002_remove_offer_product_offer_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='brand',
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
