# Generated by Django 4.1.5 on 2023-01-31 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('offers', '0003_remove_offer_brand_offer_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.brand'),
        ),
    ]
