# Generated by Django 4.1.5 on 2023-01-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='product',
            new_name='brand',
        ),
    ]
