# Generated by Django 4.1.5 on 2023-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_rename_product_offer_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
