# Generated by Django 4.1.5 on 2023-01-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_id',
            field=models.IntegerField(default=1),
        ),
    ]
