# Generated by Django 4.1.5 on 2023-01-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_banner_banner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/brand_image/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/category_image/'),
        ),
    ]
