# Generated by Django 4.1.5 on 2023-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='GSTIN',
            field=models.CharField(default=2, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
