# Generated by Django 4.1.5 on 2023-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='GSTIN',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
