# Generated by Django 4.1.5 on 2023-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
