# Generated by Django 4.1.5 on 2023-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
