# Generated by Django 4.1.5 on 2023-01-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
