# Generated by Django 4.1.5 on 2023-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='otp',
        ),
        migrations.AddField(
            model_name='users',
            name='otps',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
