# Generated by Django 4.1.5 on 2023-01-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_users_is_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_allowed',
        ),
    ]
