# Generated by Django 4.1.5 on 2023-01-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_users_otp_users_otps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otps',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
