# Generated by Django 4.1.5 on 2023-01-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_full_name_address_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
