# Generated by Django 4.1.5 on 2023-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Credit Card', 'Credit Card'), ('Netbanking', 'Netbanking'), ('UPI', 'UPI')], max_length=50),
        ),
    ]
