# Generated by Django 4.1.5 on 2023-01-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id',
            new_name='cart_id',
        ),
    ]
