# Generated by Django 4.1.5 on 2023-01-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_items_coupon_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='no_of_coupons',
        ),
    ]
