# Generated by Django 4.1.5 on 2023-01-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_coupon_no_of_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
    ]
