# Generated by Django 4.1.5 on 2023-01-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_coupon_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minimun_amount',
            new_name='minimum_amount',
        ),
    ]
