# Generated by Django 4.1.5 on 2023-02-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_minimun_amount_coupon_minimum_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
